##**************************************************************************
##
## Description -------------------------------------------------------------
##
##**************************************************************************
##*
"""
DTO for the API Response of the funifier API.
"""
##*
##*
##* Modifications:
##* Date                User        Description
##* ------------------------------------------------------------------------
##* 2023-04-11          bettlerd    created script
##*
##*

from typing import Any
from dataclasses import dataclass

@dataclass
class APIResponseDTO:
    """
    DTO for the API Response of the funifier API.

    Code generated by https://json2csharp.com/code-converters/json-to-python
    """
    errorMessage: str
    errorCode: int
    documentation: str

    @staticmethod
    def from_dict(obj: Any) -> 'APIResponseDTO':
        _errorMessage = str(obj.get("errorMessage"))
        _errorCode = int(obj.get("errorCode"))
        _documentation = str(obj.get("documentation"))
        
        return APIResponseDTO(_errorMessage, _errorCode, _documentation)

# Example Usage
# import json
# jsonstring = json.loads(myjsonstring)
# root = APIResponseDTO.from_dict(jsonstring)
